### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by benpious** [uber/cyborg#69]
We should support SwiftPM. 

But, per [this](https://forums.swift.org/t/referring-to-libxml2-in-swift-package-description/28880) thread, we can't use it because of some issue with the libxml2 module map.

**Comment by dreampiggy** [comment]
I think Xcode 11.4 already fix the modulemap for libxml2. It’s time to support SPM.

See: https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes

**Comment by benpious** [comment]
Thank you for pointing this out! I'll investigate the possibility.
